(function(){
'use strict';
const E=window.AstroEngine;
if(!E)throw new Error('Centre de compte : moteur indisponible');
const state={open:false,mode:'home',account:null,busy:false,message:'',error:'',promo:'',resetToken:'',resetEmail:''};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function token(){return localStorage.getItem('astro-token')||''}
function authHeaders(json=false){const h={};if(json)h['Content-Type']='application/json';const t=token();if(t)h.Authorization='Bearer '+t;const admin=localStorage.getItem('astro-admin-key');if(admin)h['x-admin-key']=admin;return h}
async function request(url,opt={}){const r=await fetch(url,opt),data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.erreur||data.error||`Erreur ${r.status}`);e.code=data.code||'';e.status=r.status;e.data=data;throw e}return data}
function root(){let el=document.getElementById('ap-account-center');if(!el){el=document.createElement('div');el.id='ap-account-center';document.body.appendChild(el)}return el}
function fmtDate(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function isAdmin(a){return !!(a&&(a.role==='admin'||a.is_admin))}
function isPremium(a){return !!(a&&(a.premium||isAdmin(a)))}
function questionCredits(a){return isAdmin(a)?'Illimitées':String(Number(a?.question_credits||0))}
function banner(){if(state.error)return`<div class="ac-banner ac-error">${esc(state.error)}</div>`;if(state.message)return`<div class="ac-banner ac-ok">${esc(state.message)}</div>`;return''}
function input(name,label,type='text',extra=''){return`<label class="ac-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" ${extra}></label>`}
function loggedOut(){if(state.mode==='signup')return`<div class="ac-kicker">Créer un compte</div><h2>Bienvenue chez Astro Paquita</h2><p class="ac-intro">Le compte sert aux fonctions IA, aux droits Premium et aux crédits de questions. Vos profils de naissance restent enregistrés sur votre appareil.</p>${banner()}<form data-ac-form="signup" class="ac-form">${input('prenom','Prénom','text','required autocomplete="given-name"')}${input('email','E-mail','email','required autocomplete="email"')}${input('password','Mot de passe','password','required minlength="6" autocomplete="new-password"')}<button class="ac-primary">Créer mon compte</button></form><button class="ac-link" data-ac-mode="login">J’ai déjà un compte</button>`;
if(state.mode==='forgot')return`<div class="ac-kicker">Mot de passe oublié</div><h2>Recevoir un lien de réinitialisation</h2><p class="ac-intro">Le lien envoyé par e-mail est valable 30 minutes. La réponse reste volontairement identique, que le compte existe ou non.</p>${banner()}<form data-ac-form="forgot" class="ac-form">${input('email','E-mail','email','required autocomplete="email"')}<button class="ac-primary">Envoyer le lien</button></form><button class="ac-link" data-ac-mode="login">← Retour à la connexion</button>`;
if(state.mode==='reset')return`<div class="ac-kicker">Nouveau mot de passe</div><h2>Réinitialiser votre accès</h2><p class="ac-intro">Choisissez un mot de passe d’au moins 8 caractères.</p>${banner()}<form data-ac-form="reset" class="ac-form">${input('password','Nouveau mot de passe','password','required minlength="8" autocomplete="new-password"')}${input('confirm','Confirmer le mot de passe','password','required minlength="8" autocomplete="new-password"')}<button class="ac-primary">Enregistrer le nouveau mot de passe</button></form>`;
return`<div class="ac-kicker">Mon compte</div><h2>Connexion</h2><p class="ac-intro">Connectez-vous pour les fonctions Premium, les réponses IA et vos crédits de questions.</p>${banner()}<form data-ac-form="login" class="ac-form">${input('email','E-mail','email','required autocomplete="email"')}${input('password','Mot de passe','password','required autocomplete="current-password"')}<button class="ac-primary">Se connecter</button></form><div class="ac-inline-links"><button class="ac-link" data-ac-mode="forgot">Mot de passe oublié ?</button><button class="ac-link" data-ac-mode="signup">Créer un compte</button></div>`}
function loggedIn(){const a=state.account||{},admin=isAdmin(a),premium=isPremium(a),expires=a.premium_expires_at?` · jusqu’au ${fmtDate(a.premium_expires_at)}`:'';return`<div class="ac-kicker">Mon compte</div><div class="ac-account-head"><div><h2>${esc(a.prenom||'Votre compte')}</h2><p>${esc(a.email||'')}</p></div><span class="ac-plan ${premium?'premium':'free'}">${admin?'Administrateur':premium?'Premium':'Gratuit'}</span></div>${banner()}<div class="ac-stats"><div><span>Formule</span><strong>${admin?'Administrateur':premium?'Premium':'Gratuite'}</strong><small>${premium&&!admin?esc(expires.replace(/^ · /,'')):' '}</small></div><div><span>Questions disponibles</span><strong>${esc(questionCredits(a))}</strong><small>${admin?'Accès illimité':'1 question offerte à la création du compte, puis packs ou codes promo'}</small></div></div>${admin?`<section class="ac-section"><div><span class="ac-section-label">Administration</span><h3>Gérer Astro Paquita</h3><p>Utilisateurs, statistiques, profils, codes promo et maintenance.</p></div><button class="ac-secondary" data-ac-action="admin">Ouvrir l’administration</button></section>`:''}${!premium?`<section class="ac-section ac-premium"><div><span class="ac-section-label">Premium</span><h3>Accéder aux prévisions futures et aux modules avancés</h3><p>Le paiement passe par Stripe. Un code de réduction peut être appliqué avant le paiement.</p></div><div class="ac-promo-row"><input id="ac-premium-code" placeholder="Code promo éventuel" value="${esc(state.promo)}"><button class="ac-primary" data-ac-action="premium">Passer Premium</button></div></section>`:`<section class="ac-section"><div><span class="ac-section-label">Premium</span><h3>Votre accès est actif</h3><p>${admin?'Les droits administrateur incluent les fonctions Premium.':`Votre formule Premium est active${esc(expires)}.`}</p></div></section>`}<section class="ac-section"><div><span class="ac-section-label">Codes promo</span><h3>Utiliser un code</h3><p>Un code peut ajouter des questions, offrir des jours Premium ou appliquer une réduction au paiement Premium.</p></div><form data-ac-form="promo" class="ac-promo-row"><input name="code" placeholder="Votre code" required><button class="ac-secondary">Appliquer</button></form></section>${!admin?`<section class="ac-section"><div><span class="ac-section-label">Ma question</span><h3>Pack de 5 questions</h3><p>Les crédits sont liés à votre compte. Un crédit n’est consommé que lorsqu’une réponse exploitable est produite.</p></div><button class="ac-secondary" data-ac-action="questions-pack">Acheter 5 questions</button></section>`:''}<section class="ac-section ac-account-actions"><button class="ac-link" data-ac-action="logout">Se déconnecter</button><button class="ac-danger" data-ac-action="delete-account">Supprimer définitivement mon compte</button></section>`}
function render(){const el=root();if(!state.open){el.innerHTML='';el.className='';return}el.className='ac-overlay';el.innerHTML=`<div class="ac-panel" role="dialog" aria-modal="true" aria-label="Mon compte"><div class="ac-top"><div class="ac-brand">Astro Paquita<small>Compte & accès</small></div><button class="ac-close" data-ac-close aria-label="Fermer">×</button></div>${state.busy?'<div class="ac-loading"><div></div></div>':''}<div class="ac-body">${state.account?loggedIn():loggedOut()}</div></div>`}
async function refreshAccount(){state.account=await E.account();return state.account}
async function open(mode){state.open=true;state.error='';state.message='';state.mode=mode||'home';if(!state.resetToken)await refreshAccount();render()}
function close(){state.open=false;state.error='';state.message='';render()}
async function work(fn){state.error='';state.message='';state.busy=true;render();try{await fn()}catch(e){state.error=e?.message||String(e)}finally{state.busy=false;render()}}
function cleanResetParams(){const u=new URL(location.href);u.searchParams.delete('reset_token');u.searchParams.delete('reset_email');history.replaceState(null,'',u.pathname+u.search+u.hash)}
async function login(form){const f=new FormData(form);await E.login(String(f.get('email')||'').trim(),String(f.get('password')||''));location.reload()}
async function signup(form){const f=new FormData(form);await E.signup(String(f.get('email')||'').trim(),String(f.get('password')||''),String(f.get('prenom')||'').trim());location.reload()}
async function forgot(form){const f=new FormData(form);const data=await request('/api/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:String(f.get('email')||'').trim()})});state.message=data.message||'Si un compte existe avec cet e-mail, un lien va être envoyé.'}
async function resetPassword(form){const f=new FormData(form),p=String(f.get('password')||''),c=String(f.get('confirm')||'');if(p!==c)throw new Error('Les deux mots de passe ne correspondent pas.');const data=await request('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:state.resetEmail,token:state.resetToken,motDePasse:p})});if(data.token)localStorage.setItem('astro-token',data.token);state.resetToken='';state.resetEmail='';cleanResetParams();state.message='Votre mot de passe a été modifié.';await refreshAccount();state.mode='home'}
async function redeemPromo(form){const f=new FormData(form),code=String(f.get('code')||'').trim().toUpperCase();const data=await request('/api/promo/redeem',{method:'POST',headers:authHeaders(true),body:JSON.stringify({code})});if(data.checkout_required){state.promo=code;state.message='Code de réduction validé. Cliquez sur « Passer Premium » pour l’appliquer au paiement.'}else{state.message=data.type==='questions_gratuites'?`${Number(data.valeur)||1} question(s) ajoutée(s) à votre compte.`:data.type==='jours_premium'?`${Number(data.valeur)||0} jour(s) Premium ajouté(s).`:'Code appliqué.';await refreshAccount()}}
async function startPremium(){const input=document.getElementById('ac-premium-code'),code=String(input?.value||state.promo||'').trim().toUpperCase();const data=await request('/api/stripe/checkout',{method:'POST',headers:authHeaders(true),body:JSON.stringify(code?{codePromo:code}:{})});if(!data.url)throw new Error('Stripe n’a pas renvoyé de lien de paiement.');location.href=data.url}
async function buyQuestions(){const data=await request('/api/stripe/questions-pack',{method:'POST',headers:authHeaders(true),body:'{}'});if(!data.url)throw new Error('Stripe n’a pas renvoyé de lien de paiement.');location.href=data.url}
async function deleteAccount(){if(!window.confirm("Supprimer définitivement votre compte Astro Paquita ? Votre abonnement Premium sera annulé. Vos profils astrologiques enregistrés localement sur cet appareil ne seront pas supprimés."))return;await request('/api/me',{method:'DELETE',headers:authHeaders(false)});E.logout();location.reload()}
async function confirmQuestionPackIfNeeded(){const u=new URL(location.href),status=u.searchParams.get('questions'),sid=u.searchParams.get('session_id');if(status!=='succes'||!sid||!token())return false;state.open=true;state.busy=true;render();try{const data=await request('/api/stripe/questions-pack/confirm?session_id='+encodeURIComponent(sid),{headers:authHeaders(false)});state.message=`Paiement validé. ${Number(data.question_credits||0)} question(s) disponible(s).`;await refreshAccount()}catch(e){state.error=e.message}finally{u.searchParams.delete('questions');u.searchParams.delete('session_id');history.replaceState(null,'',u.pathname+u.search+u.hash);state.busy=false;render()}return true}
async function handleReturnFromPremium(){const u=new URL(location.href),status=u.searchParams.get('paiement');if(status!=='succes')return false;state.open=true;state.busy=true;render();try{await refreshAccount();state.message=isPremium(state.account)?'Paiement Premium confirmé. Votre accès est actif.':'Paiement reçu. Le statut Premium sera confirmé par Stripe.'}finally{u.searchParams.delete('paiement');history.replaceState(null,'',u.pathname+u.search+u.hash);state.busy=false;render()}return true}
document.addEventListener('click',e=>{const account=e.target.closest?.('[data-account]');if(account){e.preventDefault();e.stopImmediatePropagation();open('home');return}if(!state.open)return;const closeBtn=e.target.closest?.('[data-ac-close]');if(closeBtn||e.target===root()){e.preventDefault();close();return}const mode=e.target.closest?.('[data-ac-mode]');if(mode){state.mode=mode.dataset.acMode;state.error='';state.message='';render();return}const act=e.target.closest?.('[data-ac-action]');if(!act)return;const action=act.dataset.acAction;if(action==='logout'){E.logout();location.reload()}else if(action==='admin'){location.href='../admin.html'}else if(action==='premium'){work(startPremium)}else if(action==='questions-pack'){work(buyQuestions)}else if(action==='delete-account'){work(deleteAccount)}},true);
document.addEventListener('submit',e=>{if(!state.open)return;const form=e.target.closest?.('[data-ac-form]');if(!form)return;e.preventDefault();const type=form.dataset.acForm;if(type==='login')work(()=>login(form));else if(type==='signup')work(()=>signup(form));else if(type==='forgot')work(()=>forgot(form));else if(type==='reset')work(()=>resetPassword(form));else if(type==='promo')work(()=>redeemPromo(form))});
(async function init(){const u=new URL(location.href);state.resetToken=u.searchParams.get('reset_token')||'';state.resetEmail=u.searchParams.get('reset_email')||'';if(state.resetToken&&state.resetEmail){state.mode='reset';state.open=true;render();return}if(await confirmQuestionPackIfNeeded())return;await handleReturnFromPremium()})();
})();
