(function(){
'use strict';
const E=()=>window.AstroEngine;
const state={route:'home',engine:false,error:'',busy:'',profile:null,account:null,days:[],natal:null,natalReport:'',dailyReport:'',year:null,yearReport:'',horizon:12,tool:null,timing:null,relation:null,child:null,question:null,modal:null,authMode:'login',profileEditor:null,cityResults:[],cityTimer:null};
const ROUTES=[['home','Accueil','⌂'],['sky','Mon ciel','✦'],['now','Maintenant','☉'],['year','Mon année','◌'],['explore','Explorer','◇']];
const DOMAINS={couple:'Amour',amour:'Amour',work:'Travail',travail:'Travail',argent:'Argent',money:'Argent',finances:'Argent',daily:'Bien-être',sante:'Bien-être',famille:'Famille',family:'Famille',voyage:'Voyage',travel:'Voyage'};
const MONTHS={janvier:0,fevrier:1,mars:2,avril:3,mai:4,juin:5,juillet:6,aout:7,septembre:8,octobre:9,novembre:10,decembre:11};
const INTENTIONS=[['argent','Argent'],['travail','Travail / emploi'],['investir','Investir / signer'],['rencontre','Rencontre'],['demenager','Déménagement'],['voyage','Voyage'],['creation','Création / projet'],['examen','Examen / concours']];
const RELTYPES=[['couple','Couple / relation existante'],['rencontre','Rencontre / début'],['ex','Ex / relation passée'],['compliquee','Relation compliquée'],['amitie','Amitié'],['famille','Famille'],['pro','Professionnel']];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateAt(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d}
function fmt(d,opt){return new Intl.DateTimeFormat('fr-FR',opt||{weekday:'short',day:'numeric'}).format(d).replace('.','')}
function domain(x){return DOMAINS[String(x||'').toLowerCase()]||String(x||'').replace(/^./,c=>c.toUpperCase())}
function dominant(rows){return [...(rows||[])].sort((a,b)=>(b.strength||b.force||0)-(a.strength||a.force||0))[0]||null}
function tone(s){if(!s)return'Stable';if(s.polarite==='positive')return'Porteuse';if(s.polarite==='difficile')return'Plus délicate';return'Contrastée'}
function sentence(s){if(!s)return'Aucun signal dominant suffisamment net ne ressort aujourd’hui.';const d=domain(s.domain||s.label);if(s.polarite==='positive')return`${d} ressort davantage aujourd’hui, dans une tonalité porteuse.`;if(s.polarite==='difficile')return`${d} demande davantage d’attention aujourd’hui.`;return`${d} est le domaine le plus actif aujourd’hui, avec une tonalité contrastée.`}
function aiText(data){if(typeof data==='string')return data;return String(data?.content?.[0]?.text||data?.text||data?.message||data?.response||'').trim()}
function markdown(text){const lines=String(text||'').replace(/\r/g,'').split('\n');let out='',list=false;const close=()=>{if(list){out+='</ul>';list=false}};const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>');for(const raw of lines){const l=raw.trim();if(!l){close();continue}if(/^###\s+/.test(l)){close();out+=`<h3>${inline(l.replace(/^###\s+/,''))}</h3>`}else if(/^##?\s+/.test(l)){close();out+=`<h2>${inline(l.replace(/^##?\s+/,''))}</h2>`}else if(/^[-•]\s+/.test(l)){if(!list){out+='<ul>';list=true}out+=`<li>${inline(l.replace(/^[-•]\s+/,''))}</li>`}else{close();out+=`<p>${inline(l)}</p>`}}close();return out}
function sentences(text,n=3){const clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return'';const parts=clean.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[clean];return parts.slice(0,n).join(' ').trim()}
function day(offset){return state.days.find(x=>x.offset===offset)||{offset,date:dateAt(offset),rows:[]}}
function daySummary(d){const s=dominant(d.rows);return{date:d.date,s,tone:tone(s),domain:s?domain(s.domain||s.label):'—'}}
function compare(a,b){const A=dominant(a.rows),B=dominant(b.rows);if(!A&&!B)return'Peu de changement : les deux journées restent calmes.';if(A&&!B)return`${domain(A.domain||A.label)} devient plus présent.`;if(!A&&B)return'La journée est moins marquée qu’hier.';if(domain(A.domain||A.label)!==domain(B.domain||B.label))return`${domain(A.domain||A.label)} prend davantage de place.`;if(A.polarite!==B.polarite)return`La tonalité de ${domain(A.domain||A.label).toLowerCase()} évolue.`;return'La dynamique reste assez proche.'}
function nav(){return ROUTES.map(([k,l,i])=>`<button data-route="${k}" class="${state.route===k?'active':''}"><b>${i}</b>${l}</button>`).join('')}
function shell(inner){const name=state.profile?.prenom||state.profile?.key||'Profil';const acct=state.account?.prenom||state.account?.email||'Compte';return `<div class="app-shell"><aside class="desktop-nav"><div class="brand">Astro Paquita<small>Votre ciel, autrement</small></div><nav>${nav()}</nav><div class="foot">Calculs : moteur V121 · nouvelle application indépendante</div></aside><div class="main"><header class="topbar"><div class="brand">Astro Paquita<small>Votre ciel, simplement</small></div><div class="spacer"></div><button class="profile-button" data-account>${esc(acct)}</button><button class="profile-button" data-profile>${esc(name)}</button></header>${state.error?`<div class="error-banner"><span>${esc(state.error)}</span><button data-dismiss>×</button></div>`:''}<main class="content">${inner}</main></div><nav class="bottom-nav">${nav()}</nav></div>${state.modal==='profile'?profileModal():''}${state.modal==='account'?accountModal():''}${state.busy?busyOverlay():''}`}
function busyOverlay(){return `<div class="busy"><div class="busy-box"><div class="eyebrow">Astro Paquita</div><h3>${esc(state.busy)}</h3><p>Les calculs restent ceux de la V121.</p><div class="loading-line"></div></div></div>`}
function compassRow(label,strong,small){return `<div class="compass-row"><b>${esc(label)}</b><strong>${esc(strong)}</strong><small>${esc(small||'')}</small></div>`}
function home(){const today=daySummary(day(0)),tom=daySummary(day(1));const watch=state.days.filter(x=>x.offset>=0&&x.offset<7).map(daySummary).find(x=>x.s&&x.s.polarite==='difficile'&&['fort','exceptionnel'].includes(String(x.s.niveau||'')));const far=state.year?.cards?.[0],name=state.profile?.prenom||'';return `<section class="screen"><div class="hero"><div class="eyebrow">Votre ciel maintenant</div><h1>${name?`Bonjour ${esc(name)}.`:'Bonjour.'}</h1><p>Pas de catalogue. Seulement ce qui ressort pour vous maintenant, puis les chemins utiles si vous souhaitez approfondir.</p></div><section class="sky-now"><div class="eyebrow">Aujourd’hui · ${esc(fmt(today.date,{weekday:'long',day:'numeric',month:'long'}))}</div><div class="sentence">${esc(sentence(today.s))}</div><div class="meta"><span class="pill">${esc(today.tone)}</span>${today.s?`<span class="pill">${esc(today.domain)}</span>`:''}</div><div class="action-row"><button class="primary-action" data-route="now">Voir ma journée</button></div></section><section class="compass"><div class="section-head"><div><div class="eyebrow">Signature Astro Paquita</div><h2 class="section-title">Votre boussole</h2></div><p>Quatre repères. Si le moteur ne trouve rien de net, la case reste calme.</p></div><div class="compass-list">${compassRow('Maintenant',today.s?`${today.tone} · ${today.domain}`:'Stable',today.s?`Signal ${today.s.niveau||'marqué'}`:'Aucun signal dominant suffisamment net')}${compassRow('Ensuite',tom.s?`${tom.tone} · ${tom.domain}`:'Stable',tom.s?'Demain':'Aucun signal dominant demain')}${compassRow('À garder en tête',watch?`${fmt(watch.date,{weekday:'long'})} · ${watch.domain}`:'Rien de particulier',watch?'Un signal exigeant ressort dans les 7 jours':'Aucune vigilance forte dans les 7 jours')}${compassRow('Plus loin',far?far.title:'Mon année',far?(far.period[0]||far.domain):'À calculer dans Mon année')}</div></section><div class="section-head"><div><div class="eyebrow">Continuer</div><h2 class="section-title">Explorer sans se perdre</h2></div><button class="text-action" data-route="explore">Décider, comprendre un lien, poser une question →</button></div></section>`}
function natalPosition(key){return state.natal?.positions?.find(x=>x.key===key)}
function sky(){const p=state.profile,n=state.natal;const sun=natalPosition('Soleil'),moon=natalPosition('Lune');return `<section class="screen"><div class="eyebrow">Qui suis-je ?</div><h1 class="screen-title">Mon ciel</h1><p class="screen-intro">Une lecture de votre structure intérieure avant le détail technique.</p>${p?`<div class="profile-line"><strong>${esc(p.prenom||'Votre profil')}</strong><span>${esc([p.date,p.heure,p.ville].filter(Boolean).join(' · '))}</span></div>`:''}${n?`<section class="signature"><div><b>Planète dominante</b><strong>${esc(n.dominantPlanet||'—')}</strong></div><div><b>Signe dominant</b><strong>${esc(n.dominantSign||'—')}</strong></div><div><b>Maison dominante</b><strong>${esc(n.dominantHouse?'Maison '+n.dominantHouse:'—')}</strong></div></section><section class="editorial-block"><h2>Vos grands repères</h2><div class="position-grid"><div><b>Soleil</b><strong>${esc(sun?.sign||'—')}</strong><small>${sun?.house?'Maison '+esc(sun.house):''}</small></div><div><b>Lune</b><strong>${esc(moon?.sign||'—')}</strong><small>${moon?.house?'Maison '+esc(moon.house):''}</small></div>${(n.positions||[]).filter(x=>['Mercure','Venus','Mars'].includes(x.key)).map(x=>`<div><b>${esc(x.name)}</b><strong>${esc(x.sign)}</strong><small>${x.house?'Maison '+esc(x.house):''}</small></div>`).join('')}</div></section><section class="editorial-block"><div class="section-head"><div><div class="eyebrow">Lecture éditoriale</div><h2>Vos grandes constantes et vos paradoxes</h2></div>${!state.natalReport?'<button class="primary-action" data-action="natal-report">Créer mon portrait</button>':'<button class="text-action" data-print>Imprimer / PDF</button>'}</div>${state.natalReport?`<article class="report print-area">${markdown(state.natalReport)}</article>`:'<p>Le texte sera construit uniquement à partir des positions, maisons et aspects calculés par V121.</p>'}</section><details class="technical"><summary>Voir les aspects les plus structurants</summary><div class="aspect-list">${(n.aspects||[]).slice(0,12).map(a=>`<div><strong>${esc(a.p1)} · ${esc(a.n)} · ${esc(a.p2)}</strong><span>Orbe ${Number(a.orb||0).toFixed(2)}°</span></div>`).join('')}</div></details>`:`<div class="empty"><strong>Le thème technique n’est pas encore préparé pour ce profil.</strong><br><button class="primary-action inline-action" data-action="prepare-natal">Préparer mon thème avec V121</button></div>`}</section>`}
function now(){const days=state.days.filter(x=>x.offset>=0&&x.offset<7).map(daySummary),t=daySummary(day(0));const rows=day(0).rows;return `<section class="screen"><div class="eyebrow">Où en suis-je ?</div><h1 class="screen-title">Maintenant</h1><p class="screen-intro">La lecture essentielle tient en quelques secondes. Le détail est volontairement secondaire.</p><section class="sky-now"><div class="eyebrow">${esc(fmt(t.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}</div><div class="sentence">${esc(sentence(t.s))}</div><div class="meta"><span class="pill">${esc(t.tone)}</span>${t.s?`<span class="pill">${esc(t.domain)}</span>`:''}</div></section><section class="editorial-block"><h2>Votre semaine en 7 jours</h2><div class="week-strip">${days.map((x,i)=>`<div class="day ${i===0?'today':''}"><b>${esc(fmt(x.date))}</b><strong>${esc(x.tone)}</strong><small>${esc(x.domain)}</small></div>`).join('')}</div></section><section class="editorial-block"><div class="section-head"><div><h2>Ce qui ressort aujourd’hui</h2><p>${esc(compare(day(0),day(-1)))}</p></div>${rows.length&&!state.dailyReport?'<button class="primary-action" data-action="daily-report">Approfondir</button>':''}</div>${rows.length?`<div class="signal-list">${rows.slice(0,3).map(s=>`<div><b>${esc(domain(s.domain||s.label))}</b><strong>${esc(tone(s))}</strong><small>Signal ${esc(s.niveau||'marqué')}</small></div>`).join('')}</div>`:`<p class="quiet">Aucun signal suffisamment net ne justifie un développement particulier aujourd’hui.</p>`}${state.dailyReport?`<article class="report print-area">${markdown(state.dailyReport)}</article><button class="text-action" data-print>Imprimer / PDF</button>`:''}</section><section class="two-notes"><div><b>Par rapport à hier</b><p>${esc(compare(day(0),day(-1)))}</p></div><div><b>Et demain ?</b><p>${esc(compare(day(1),day(0)))}</p></div></section></section>`}
function parseFrenchDate(txt){const s=String(txt||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const m=s.match(/(\d{1,2})\s+(janvier|fevrier|mars|avril|mai|juin|juillet|aout|septembre|octobre|novembre|decembre)\s+(\d{4})/);if(!m)return null;return new Date(Number(m[3]),MONTHS[m[2]],Number(m[1]),12)}
function eventsForMonths(months=12){const all=state.year?.cards||[];if(months>=24)return all;const lim=new Date();lim.setHours(23,59,59,999);lim.setMonth(lim.getMonth()+months);return all.filter(c=>{const d=parseFrenchDate((c.period||[]).join(' ')+' '+c.raw);return !d||d<=lim})}
function visibleEvents(){return eventsForMonths(state.horizon)}
function cleanPeriod(s){return String(s||'').replace(/\d+\s+familles? de techniques/gi,'plusieurs indicateurs').replace(/\s+·\s+·/g,' · ')}
function year(){const events=visibleEvents(),annual=eventsForMonths(12);return `<section class="screen"><div class="eyebrow">Qu’est-ce qui vient ensuite ?</div><h1 class="screen-title">Mon année</h1><p class="screen-intro">12 mois d’abord. Les 24 mois restent une vue secondaire.</p><section class="editorial-block"><div class="section-head"><div><div class="eyebrow">Temps forts</div><h2>Les périodes qui ressortent réellement</h2></div>${!state.year?'<button class="primary-action" data-action="load-year">Calculer mes temps forts</button>':'<button class="text-action" data-print>Imprimer / PDF</button>'}</div>${state.year?`<div class="horizon"><button data-horizon="12" class="${state.horizon===12?'active':''}">12 mois</button><button data-horizon="24" class="${state.horizon===24?'active':''}">Voir plus loin · 24 mois</button></div>${state.horizon===12&&annual.length?`${state.yearReport?`<article class="report result-card print-area">${markdown(state.yearReport)}</article>`:`<div class="result-card"><div class="eyebrow">Lecture annuelle</div><h2>Le fil de vos 12 prochains mois</h2><p>Une synthèse rédigée uniquement à partir des périodes que V121 vient de détecter, sans ajouter d’événement ni de date.</p><button class="primary-action" data-action="year-report">Créer ma lecture annuelle</button></div>`}`:state.horizon===24?'<p class="quiet">La vue 24 mois reste volontairement une chronologie brute des périodes V121. La synthèse éditoriale concerne uniquement les 12 prochains mois.</p>':''}<div class="print-area">${events.length?`<div class="timeline">${events.map(e=>`<article><div class="timeline-mark"></div><div class="timeline-body"><span class="eyebrow">${esc(e.domain||e.trend||'Période')}</span><h3>${esc(e.title||'Période importante')}</h3>${e.trend?`<span class="tone-label">${esc(e.trend)}</span>`:''}${(e.period||[]).map(x=>`<p>${esc(cleanPeriod(x))}</p>`).join('')}${e.details?.length?`<details><summary>Comprendre cette période</summary>${e.details.slice(0,4).map(x=>`<p>${esc(x)}</p>`).join('')}</details>`:''}</div></article>`).join('')}</div>`:'<p class="quiet">Aucune période ne franchit le seuil retenu sur cet horizon.</p>'}</div>`:'<p>Le calcul utilise directement le détecteur d’événements V121. La nouvelle interface ne recalcule rien.</p>'}</section></section>`}
function explore(){if(state.tool==='timing')return timingTool();if(state.tool==='relation')return relationTool();if(state.tool==='child')return childTool();if(state.tool==='question')return questionTool();return `<section class="screen"><div class="eyebrow">Explorer</div><h1 class="screen-title">Qu’avez-vous besoin de comprendre ?</h1><p class="screen-intro">On part de votre besoin, pas du nom d’une technique astrologique.</p><div class="explore-list"><button class="explore-item" data-tool="timing"><div><h3>J’ai une décision à prendre</h3><p>Trouver des fenêtres adaptées à une intention précise, sans promettre de date parfaite.</p></div><span>→</span></button><button class="explore-item" data-tool="relation"><div><h3>Je veux comprendre une relation</h3><p>Ce qui rapproche, ce qui demande des ajustements et le fonctionnement de chacun dans le lien.</p></div><span>→</span></button><button class="explore-item" data-tool="child"><div><h3>Je veux comprendre un enfant</h3><p>Forces, sensibilités, sécurité, apprentissage, autonomie et ce qui l’aide à grandir.</p></div><span>→</span></button><button class="explore-item" data-tool="question"><div><h3>J’ai une question précise</h3><p>Une réponse directe d’abord, puis seulement les signaux utiles et les nuances.</p></div><span>→</span></button></div></section>`}
function toolBack(){return'<button class="text-action back-tool" data-tool="">← Explorer</button>'}
function timingTool(){return `<section class="screen">${toolBack()}<div class="eyebrow">Décider</div><h1 class="screen-title">Le bon moment</h1><p class="screen-intro">Choisissez votre intention. Le moteur V121 cherche ses fenêtres ; cette interface ne modifie ni score ni date.</p><form class="tool-form" data-form="timing"><label>Mon intention<select name="intention">${INTENTIONS.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select></label><button class="primary-action">Chercher mes fenêtres</button></form>${state.timing?`<section class="result-card print-area"><div class="eyebrow">Fenêtres détectées</div><h2>${esc(state.timing.title||'Le bon moment')}</h2><p class="result-sub">${esc(cleanPeriod(String(state.timing.subtitle||'').replace(/\d+\/100/g,'').replace(/Scan 10 ans/gi,'')))}</p>${state.timing.windows?.length?`<div class="window-list">${state.timing.windows.map(x=>`<div>${esc(cleanPeriod(x).replace(/\d+\/100/g,''))}</div>`).join('')}</div>`:''}${state.timing.report?`<details><summary>Pourquoi ces périodes ressortent ?</summary><div class="report plain">${esc(state.timing.report)}</div></details>`:''}</section>`:''}</section>`}
function relationTool(){const all=E().profiles(),active=E().activeKey(),others=Object.entries(all).filter(([k])=>k!==active);const direct=sentences(state.relation?.report,3);return `<section class="screen">${toolBack()}<div class="eyebrow">Comprendre un lien</div><h1 class="screen-title">Relations</h1><p class="screen-intro">Pas de note-verdict. On regarde la dynamique du lien et ses ajustements.</p><form class="tool-form" data-form="relation"><label>Comparer avec<select name="other">${others.map(([k,p])=>`<option value="${esc(k)}">${esc(p.prenom||k)}</option>`).join('')}</select></label><label>Type de relation<select name="type">${RELTYPES.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select></label><button class="primary-action" ${others.length?'':'disabled'}>Analyser la relation</button></form>${!others.length?'<p class="quiet">Ajoutez au moins un autre profil de naissance pour utiliser cette lecture.</p>':''}${state.relation?`<section class="result-card print-area"><div class="eyebrow">En bref</div><h2>${esc(state.relation.title||'Votre relation')}</h2><p class="lead-answer">${esc(direct)}</p><details><summary>Lire l’analyse complète</summary><div class="report plain">${esc(state.relation.report||'')}</div>${state.relation.periods?`<div class="report plain">${esc(state.relation.periods)}</div>`:''}</details></section>`:''}</section>`}
function ageFrom(date){if(!date)return null;const d=new Date(date),n=new Date();if(Number.isNaN(d.getTime()))return null;let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function childTool(){const all=E().profiles();return `<section class="screen">${toolBack()}<div class="eyebrow">Grandir</div><h1 class="screen-title">Portrait enfant</h1><p class="screen-intro">Forces, sensibilités, sécurité, apprentissage et autonomie. Aucune destinée adulte figée.</p><form class="tool-form" data-form="child"><label>Profil de l’enfant<select name="child">${Object.entries(all).map(([k,p])=>`<option value="${esc(k)}">${esc(p.prenom||k)}${ageFrom(p.date)!=null?' · '+ageFrom(p.date)+' ans':''}</option>`).join('')}</select></label><button class="primary-action">Créer le portrait enfant</button></form>${state.child?`<article class="report result-card print-area">${markdown(state.child)}</article>`:''}</section>`}
function questionTool(){const direct=sentences(state.question?.report,4);return `<section class="screen">${toolBack()}<div class="eyebrow">Question précise</div><h1 class="screen-title">Ma question</h1><p class="screen-intro">La réponse commence directement. Les détails restent disponibles sans envahir l’écran.</p><form class="tool-form" data-form="question"><label>Domaine<select name="domain"><option value="general">Général</option><option value="amour">Amour</option><option value="travail">Travail</option><option value="argent">Argent</option><option value="famille">Famille</option><option value="sante">Bien-être</option><option value="voyage">Voyage</option></select></label><label>Votre question<textarea name="q" rows="5" minlength="10" required placeholder="Écrivez votre question simplement…"></textarea></label><button class="primary-action">Analyser ma question</button></form>${state.question?`<section class="result-card print-area"><div class="eyebrow">Réponse directe</div><h2>${esc(state.question.title||'Votre question')}</h2><p class="lead-answer">${esc(direct)}</p><details><summary>Voir les signaux, nuances et périodes</summary><div class="report plain">${esc(state.question.report||'')}</div></details></section>`:''}</section>`}
function blankProfile(){return{oldKey:'',prenom:'',date:'',heure:'',ville:'',lat:'',lon:'',tz:'Europe/Paris',genre:'N'}}
function profileEditor(){const p=state.profileEditor||blankProfile();return `<div class="profile-editor"><div class="section-head"><div><div class="eyebrow">${p.oldKey?'Modifier':'Nouveau'} profil</div><h3>Données de naissance</h3></div><button class="text-action" type="button" data-profile-cancel>Annuler</button></div><form class="tool-form" data-form="profile"><input type="hidden" name="oldKey" value="${esc(p.oldKey||'')}"><input type="hidden" name="lat" value="${esc(p.lat||'')}"><input type="hidden" name="lon" value="${esc(p.lon||'')}"><input type="hidden" name="tz" value="${esc(p.tz||'Europe/Paris')}"><label>Prénom<input name="prenom" value="${esc(p.prenom||'')}" required autocomplete="off"></label><div class="profile-fields"><label>Date de naissance<input name="date" value="${esc(p.date||'')}" placeholder="JJ/MM/AAAA" required inputmode="numeric"></label><label>Heure de naissance<input name="heure" value="${esc(p.heure||'')}" placeholder="HH:MM" required inputmode="numeric"></label></div><label>Ville de naissance<div class="city-field"><input name="ville" value="${esc(p.ville||'')}" placeholder="Commencez à taper une ville…" required autocomplete="off">${state.cityResults.length?`<div class="city-results">${state.cityResults.map((c,i)=>`<button type="button" data-city-index="${i}"><strong>${esc(c.label)}</strong><small>${esc(c.tz)}</small></button>`).join('')}</div>`:''}</div></label>${p.lat&&p.lon?`<p class="coord-ok">✓ Coordonnées V121 : ${esc(Number(p.lat).toFixed(4))}, ${esc(Number(p.lon).toFixed(4))} · ${esc(p.tz||'Europe/Paris')}</p>`:'<p class="quiet">Sélectionnez la ville dans les résultats afin de conserver les coordonnées et le fuseau utilisés par V121.</p>'}<label>Genre<select name="genre"><option value="N" ${p.genre==='N'?'selected':''}>Non renseigné / autre</option><option value="F" ${p.genre==='F'?'selected':''}>Femme</option><option value="H" ${p.genre==='H'?'selected':''}>Homme</option></select></label><button class="primary-action">${p.oldKey?'Enregistrer les modifications':'Créer ce profil'}</button></form></div>`}
function profileModal(){const all=E().profiles(),active=E().activeKey();return `<div class="modal" data-close><div class="modal-box profile-modal-box" onclick="event.stopPropagation()"><div class="section-head"><div><div class="eyebrow">Profil de naissance</div><h2>${state.profileEditor?'Votre profil':'Choisir un profil'}</h2></div><button class="text-action" data-close>Fermer</button></div>${state.profileEditor?profileEditor():`<div class="profile-list">${Object.entries(all).map(([k,p])=>`<div class="profile-row ${k===active?'active':''}"><button data-profile-key="${esc(k)}"><strong>${esc(p.prenom||k)}</strong><br><small>${esc([p.date,p.heure,p.ville].filter(Boolean).join(' · '))}</small></button><div class="profile-row-actions"><button type="button" data-profile-edit="${esc(k)}">Modifier</button><button type="button" data-profile-delete="${esc(k)}" class="danger-action">Supprimer</button></div></div>`).join('')||'<p class="quiet">Aucun profil enregistré sur cet appareil.</p>'}</div><button class="primary-action profile-new" type="button" data-profile-new>+ Ajouter un profil</button>`}</div></div>`}
function accountModal(){if(state.account)return `<div class="modal" data-close><div class="modal-box" onclick="event.stopPropagation()"><div class="section-head"><div><div class="eyebrow">Mon compte</div><h2>${esc(state.account.prenom||state.account.email||'Compte')}</h2></div><button class="text-action" data-close>Fermer</button></div><p class="screen-intro">${esc(state.account.email||'')}</p><div class="meta"><span class="pill">${state.account.premium||state.account.role==='admin'?'Premium':'Gratuit'}</span></div><div class="action-row"><button class="text-action" data-logout>Se déconnecter</button></div></div></div>`;const signup=state.authMode==='signup';return `<div class="modal" data-close><div class="modal-box" onclick="event.stopPropagation()"><div class="section-head"><div><div class="eyebrow">${signup?'Créer un compte':'Connexion'}</div><h2>${signup?'Bienvenue':'Bon retour'}</h2></div><button class="text-action" data-close>Fermer</button></div><form class="tool-form" data-form="auth">${signup?'<label>Prénom<input name="prenom" required></label>':''}<label>Email<input name="email" type="email" required></label><label>Mot de passe<input name="password" type="password" required minlength="6"></label><button class="primary-action">${signup?'Créer mon compte':'Se connecter'}</button></form><button class="text-action" data-auth-mode="${signup?'login':'signup'}">${signup?'J’ai déjà un compte':'Créer un compte gratuit'}</button></div></div>`}
function screen(){if(state.route==='sky')return sky();if(state.route==='now')return now();if(state.route==='year')return year();if(state.route==='explore')return explore();return home()}
function render(){document.getElementById('app').innerHTML=shell(screen());bind()}
async function run(label,fn){state.error='';state.busy=label;render();try{await fn()}catch(e){state.error=e?.message||String(e)}finally{state.busy='';render()}}
function profileFromForm(form){const f=new FormData(form);return{oldKey:String(f.get('oldKey')||''),prenom:String(f.get('prenom')||''),date:String(f.get('date')||''),heure:String(f.get('heure')||''),ville:String(f.get('ville')||''),lat:String(f.get('lat')||''),lon:String(f.get('lon')||''),tz:String(f.get('tz')||'Europe/Paris'),genre:String(f.get('genre')||'N')}}
async function refreshAfterProfileChange(){state.profile=E().profile();state.natal=null;state.natalReport='';state.year=null;state.yearReport='';state.dailyReport='';state.timing=state.relation=state.child=state.question=null;await loadCore()}
function bind(){
 document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{state.route=b.dataset.route;state.tool=null;location.hash=state.route;render()}));
 document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{state.modal='profile';state.profileEditor=null;state.cityResults=[];render()}));
 document.querySelectorAll('[data-account]').forEach(b=>b.addEventListener('click',()=>{state.modal='account';render()}));
 document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',e=>{if(e.currentTarget===e.target||e.currentTarget.matches('button')){state.modal=null;state.profileEditor=null;state.cityResults=[];render()}}));
 document.querySelectorAll('[data-dismiss]').forEach(b=>b.addEventListener('click',()=>{state.error='';render()}));
 document.querySelectorAll('[data-print]').forEach(b=>b.addEventListener('click',()=>window.print()));
 document.querySelectorAll('[data-profile-key]').forEach(b=>b.addEventListener('click',()=>run('Chargement du profil…',async()=>{await E().selectProfile(b.dataset.profileKey);state.profile=E().profile();state.modal=null;state.profileEditor=null;state.cityResults=[];await refreshAfterProfileChange()})));
 document.querySelector('[data-profile-new]')?.addEventListener('click',()=>{state.profileEditor=blankProfile();state.cityResults=[];render()});
 document.querySelectorAll('[data-profile-edit]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.profileEdit,p=E().profiles()[k];if(!p)return;state.profileEditor={oldKey:k,...p};state.cityResults=[];render()}));
 document.querySelector('[data-profile-cancel]')?.addEventListener('click',()=>{state.profileEditor=null;state.cityResults=[];render()});
 document.querySelectorAll('[data-profile-delete]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.profileDelete,p=E().profiles()[k];if(!p)return;if(!window.confirm(`Supprimer le profil ${p.prenom||k} ?`))return;run('Suppression du profil…',async()=>{await E().deleteProfile(k);state.profileEditor=null;state.cityResults=[];await refreshAfterProfileChange()})}));
 const pf=document.querySelector('[data-form="profile"]');
 if(pf){pf.addEventListener('submit',e=>{e.preventDefault();const p=profileFromForm(e.currentTarget);run(p.oldKey?'Mise à jour du profil…':'Création du profil…',async()=>{await E().saveProfile(p,p.oldKey);state.profileEditor=null;state.cityResults=[];state.modal='profile';await refreshAfterProfileChange()})});const city=pf.querySelector('[name="ville"]');city?.addEventListener('input',()=>{const current=profileFromForm(pf);state.profileEditor=current;state.cityResults=[];clearTimeout(state.cityTimer);const q=city.value.trim();if(q.length<2){render();return}state.cityTimer=setTimeout(async()=>{try{const rows=await E().searchCities(q);if(!state.profileEditor||String(state.profileEditor.ville).trim()!==q)return;state.cityResults=rows;render()}catch(e){}},350)});}
 document.querySelectorAll('[data-city-index]').forEach(b=>b.addEventListener('click',()=>{const c=state.cityResults[Number(b.dataset.cityIndex)];if(!c||!state.profileEditor)return;state.profileEditor={...state.profileEditor,ville:`${c.nom} (${c.pays})`,lat:String(c.lat),lon:String(c.lon),tz:c.tz||'Europe/Paris'};state.cityResults=[];render()}));
 document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{state.tool=b.dataset.tool||null;state.timing=state.relation=state.child=state.question=null;render()}));
 document.querySelectorAll('[data-horizon]').forEach(b=>b.addEventListener('click',()=>{state.horizon=Number(b.dataset.horizon);render()}));
 document.querySelector('[data-action="prepare-natal"]')?.addEventListener('click',()=>run('Préparation de votre thème V121…',async()=>{const r=await E().prepareNatal();state.natal=r.meta;state.natalReport=''}));
 document.querySelector('[data-action="natal-report"]')?.addEventListener('click',()=>run('Construction de votre portrait…',generateNatalReport));
 document.querySelector('[data-action="daily-report"]')?.addEventListener('click',()=>run('Lecture de votre journée…',generateDailyReport));
 document.querySelector('[data-action="load-year"]')?.addEventListener('click',()=>run('Recherche des périodes réellement marquantes…',async()=>{state.yearReport='';state.year=await E().events24()}));
 document.querySelector('[data-action="year-report"]')?.addEventListener('click',()=>run('Construction de votre lecture annuelle…',generateYearReport));
 document.querySelector('[data-form="timing"]')?.addEventListener('submit',e=>{e.preventDefault();const v=new FormData(e.currentTarget).get('intention');run('Recherche de vos fenêtres…',async()=>{state.timing=await E().timing(v)})});
 document.querySelector('[data-form="relation"]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);run('Analyse de la relation…',async()=>{state.relation=await E().relation(f.get('other'),f.get('type'))})});
 document.querySelector('[data-form="child"]')?.addEventListener('submit',e=>{e.preventDefault();const key=new FormData(e.currentTarget).get('child');run('Lecture du thème de l’enfant…',()=>generateChild(key))});
 document.querySelector('[data-form="question"]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),q=String(f.get('q')||'').trim();run('Analyse de votre question…',async()=>{state.question=await E().question(q,f.get('domain'))})});
 document.querySelector('[data-form="auth"]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),email=f.get('email'),password=f.get('password'),prenom=f.get('prenom');run(state.authMode==='signup'?'Création du compte…':'Connexion…',async()=>{if(state.authMode==='signup')await E().signup(email,password,prenom);else await E().login(email,password);state.account=await E().account();state.modal=null})});
 document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>{state.authMode=b.dataset.authMode;render()}));
 document.querySelector('[data-logout]')?.addEventListener('click',()=>{E().logout();state.account=null;state.modal=null;render()});
}
async function generateNatalReport(){const n=state.natal;if(!n)throw new Error('Préparez d’abord le thème V121');const p=state.profile||{};const positions=(n.positions||[]).map(x=>`${x.name}: ${x.sign}, maison ${x.house||'non déterminée'}`).join('\n');const aspects=(n.aspects||[]).slice(0,24).map(x=>`${x.p1} ${x.n} ${x.p2}, orbe ${Number(x.orb||0).toFixed(2)}°, ${x.nature}`).join('\n');const data=await E().ai({feature:'natal',featureContext:{engine:'V121',product:'next'},model:'claude-sonnet-4-6',max_tokens:3500,system:'Tu rédiges un portrait astrologique éditorial premium à partir EXCLUSIVEMENT de données déjà calculées par le moteur V121. Tu ne recalcules rien et tu n’inventes aucune position, maison, aspect ou dominante. Commence par 3 à 5 grandes constantes, puis Vos paradoxes. Continue avec manière d’agir, monde émotionnel, relations, réalisation/ressources, sécurité et ce qui ressource. Chaque interprétation doit être reliée à des éléments fournis. Langage clair, concret, sans jargon inutile, sans destinée figée.',messages:[{role:'user',content:`Profil: ${p.prenom||''} · ${p.date||''} · ${p.heure||''} · ${p.ville||''}\nDominantes V121: planète ${n.dominantPlanet}; signe ${n.dominantSign}; maison ${n.dominantHouse}.\n\nPOSITIONS\n${positions}\n\nASPECTS\n${aspects}`}]});state.natalReport=aiText(data);if(!state.natalReport)throw new Error('Portrait vide')}
async function generateDailyReport(){const cur=day(0),prev=day(-1),tom=day(1);if(!cur.rows.length)throw new Error('Aucun signal suffisamment net aujourd’hui');const data=await E().ai({feature:'forecast_today',featureContext:{engine:'V121',date:new Date().toISOString().slice(0,10)},model:'claude-sonnet-4-6',max_tokens:1200,system:'Tu rédiges une prévision quotidienne premium uniquement à partir des signaux V121 fournis. Aucun horoscope générique. Structure: À retenir (2 phrases), Ce qui ressort aujourd’hui (1 à 3 domaines max), Point d’attention seulement si un signal difficile existe, Comment utiliser cette journée, Par rapport à hier, Et demain ?, puis Pourquoi cette journée ressort ? en quelques lignes. Si un domaine ne ressort pas, ne le remplis pas. Aucune certitude événementielle.',messages:[{role:'user',content:`AUJOURD’HUI\n${JSON.stringify(cur.rows)}\n\nHIER\n${JSON.stringify(prev.rows)}\n\nDEMAIN\n${JSON.stringify(tom.rows)}`}]});state.dailyReport=aiText(data);if(!state.dailyReport)throw new Error('Prévision vide')}
async function generateYearReport(){if(!state.year)throw new Error('Calculez d’abord vos temps forts V121');const events=eventsForMonths(12);if(!events.length)throw new Error('Aucune période suffisamment marquante sur les 12 prochains mois');const p=state.profile||{};const source=events.map((e,i)=>({ordre:i+1,domaine:e.domain||'',titre:e.title||'',tonalite:e.trend||'',periodes:(e.period||[]).map(cleanPeriod),details:(e.details||[]).slice(0,6)}));const data=await E().ai({feature:'forecast_year',featureContext:{engine:'V121',product:'next',horizon_months:12},model:'claude-sonnet-4-6',max_tokens:3000,system:'Tu rédiges une lecture annuelle premium à partir EXCLUSIVEMENT des périodes déjà détectées par le moteur V121 et fournies ci-dessous. Tu ne recalcules rien. Tu n’ajoutes aucune date, aucun domaine, aucun événement, aucune probabilité et aucune causalité qui ne figurent pas dans les données. N’utilise pas de remplissage astrologique générique. Si les données ne soutiennent pas un sujet, dis simplement qu’il ne ressort pas nettement. Structure: 1. Fil de l’année — 2 à 4 axes réellement dominants; 2. Périodes clés — dans l’ordre chronologique avec dates strictement reprises; 3. Domaines qui reviennent; 4. Points de vigilance uniquement s’ils sont réellement présents; 5. Ce qui reste neutre ou non signalé. Langage concret, sans jargon technique, sans certitude événementielle et sans dramatisation.',messages:[{role:'user',content:`Profil: ${p.prenom||''}. Période: les 12 prochains mois à partir d’aujourd’hui.\n\nDONNÉES V121 À UTILISER STRICTEMENT\n${JSON.stringify(source,null,2)}`}]});state.yearReport=aiText(data);if(!state.yearReport)throw new Error('Lecture annuelle vide')}
async function generateChild(key){const all=E().profiles(),p=all[key];if(!p)throw new Error('Profil introuvable');const age=ageFrom(p.date);if(age!=null&&age>17)throw new Error('Choisissez un profil de moins de 18 ans');let n=await E().natalTechnicalFor(key);if(!n){const prepared=await E().prepareNatalFor(key);n=prepared.meta}if(!n)throw new Error('Thème natal V121 indisponible');const positions=(n.positions||[]).map(x=>`${x.name}: ${x.sign}, maison ${x.house||'non déterminée'}`).join('\n');const aspects=(n.aspects||[]).slice(0,20).map(x=>`${x.p1} ${x.n} ${x.p2}, orbe ${Number(x.orb||0).toFixed(2)}°`).join('\n');const data=await E().ai({feature:'natal',featureContext:{engine:'V121',child:true,age},model:'claude-sonnet-4-6',max_tokens:2600,system:'Tu rédiges un portrait astrologique d’enfant uniquement à partir des calculs V121 fournis. Parle de forces, sensibilités, besoins de sécurité, apprentissage, communication, autonomie, rapport aux règles, socialisation, créativité et ce qui aide cet enfant à grandir. Adapte le vocabulaire à son âge. Ne prédis jamais métier futur, vie conjugale, sexualité, revenus ou destinée adulte figée. Aucun diagnostic médical ou psychologique.',messages:[{role:'user',content:`Enfant: ${p.prenom||''}, âge ${age??'non précisé'} ans.\nDominantes V121: ${n.dominantPlanet}, ${n.dominantSign}, maison ${n.dominantHouse}.\nPOSITIONS\n${positions}\nASPECTS\n${aspects}`}]});state.child=aiText(data);if(!state.child)throw new Error('Portrait vide')}
async function loadSignals(){state.days=[];for(let i=-1;i<=7;i++){const date=dateAt(i);let rows=[];try{rows=await E().dailySignals(date,'marque')}catch(e){}state.days.push({offset:i,date,rows})}}
async function loadCore(){state.profile=E().profile();state.account=await E().account();await loadSignals();try{state.natal=await E().natalTechnical()}catch(e){state.natal=null}}
async function boot(){state.route=(location.hash||'#home').slice(1);if(!ROUTES.some(x=>x[0]===state.route))state.route='home';render();try{await E().waitReady();state.engine=true;await loadCore()}catch(e){state.error=e.message||String(e)}render()}
window.addEventListener('hashchange',()=>{const r=(location.hash||'#home').slice(1);if(ROUTES.some(x=>x[0]===r)){state.route=r;state.tool=null;render()}});boot();
})();
