(function(){
'use strict';
const E=()=>window.AstroEngine;
const state={route:'home',engine:false,error:'',profile:null,days:[],modal:false};
const ROUTES=[['home','Accueil','⌂'],['sky','Mon ciel','✦'],['now','Maintenant','☉'],['year','Mon année','◌'],['explore','Explorer','◇']];
const DOMAINS={couple:'Amour',amour:'Amour',work:'Travail',travail:'Travail',argent:'Argent',money:'Argent',finances:'Argent',daily:'Bien-être',sante:'Bien-être',famille:'Famille',family:'Famille',voyage:'Voyage',travel:'Voyage'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateAt(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d}
function fmt(d,opt){return new Intl.DateTimeFormat('fr-FR',opt||{weekday:'short',day:'numeric'}).format(d).replace('.','')}
function domain(x){return DOMAINS[String(x||'').toLowerCase()]||String(x||'').replace(/^./,c=>c.toUpperCase())}
function dominant(rows){return [...(rows||[])].sort((a,b)=>(b.strength||b.force||0)-(a.strength||a.force||0))[0]||null}
function tone(s){if(!s)return'Stable';if(s.polarite==='positive')return'Porteuse';if(s.polarite==='difficile')return'Plus délicate';return'Contrastée'}
function sentence(s){if(!s)return'Aucun signal dominant suffisamment net ne ressort aujourd’hui.';const d=domain(s.domain||s.label);if(s.polarite==='positive')return`${d} ressort davantage aujourd’hui, dans une tonalité porteuse.`;if(s.polarite==='difficile')return`${d} demande davantage d’attention aujourd’hui.`;return`${d} est le domaine le plus actif aujourd’hui, avec une tonalité contrastée.`}
function nav(){return ROUTES.map(([k,l,i])=>`<button data-route="${k}" class="${state.route===k?'active':''}"><b>${i}</b>${l}</button>`).join('')}
function shell(inner){const name=state.profile?.prenom||state.profile?.key||'Profil';return `<div class="app-shell"><aside class="desktop-nav"><div class="brand">Astro Paquita<small>Nouvelle expérience</small></div><nav>${nav()}</nav><div class="foot">Moteur astrologique V121 · interface entièrement nouvelle</div></aside><div class="main"><header class="topbar"><div class="brand">Astro Paquita<small>Votre ciel, simplement</small></div><div class="spacer"></div><span class="status">${state.engine?'Moteur prêt':'Connexion au moteur…'}</span><button class="profile-button" data-profile>${esc(name)}</button></header><main class="content">${inner}</main></div><nav class="bottom-nav">${nav()}</nav></div>${state.modal?profileModal():''}`}
function compassRow(label,strong,small){return `<div class="compass-row"><b>${esc(label)}</b><strong>${esc(strong)}</strong><small>${esc(small||'')}</small></div>`}
function daySummary(d){const s=dominant(d.rows);return{date:d.date,s,tone:tone(s),domain:s?domain(s.domain||s.label):'—'}}
function home(){const today=daySummary(state.days[0]||{date:dateAt(0),rows:[]}),tom=daySummary(state.days[1]||{date:dateAt(1),rows:[]});const watch=state.days.slice(0,7).map(daySummary).find(x=>x.s&&x.s.polarite==='difficile'&&['fort','exceptionnel'].includes(String(x.s.niveau||'')));const name=state.profile?.prenom||'';return `<section class="screen"><div class="hero"><div class="eyebrow">Votre ciel maintenant</div><h1>${name?`Bonjour ${esc(name)}.`:'Bonjour.'}</h1><p>Une lecture volontairement claire : ce qui ressort maintenant, ce qui évolue et ce qui mérite vraiment votre attention.</p></div><section class="sky-now"><div class="eyebrow">Aujourd’hui · ${esc(fmt(today.date,{weekday:'long',day:'numeric',month:'long'}))}</div><div class="sentence">${esc(sentence(today.s))}</div><div class="meta"><span class="pill">${esc(today.tone)}</span>${today.s?`<span class="pill">${esc(today.domain)}</span><span class="pill">Signal ${esc(today.s.niveau||'marqué')}</span>`:''}</div><div style="margin-top:22px"><button class="primary-action" data-route="now">Voir ma journée</button></div></section><section class="compass"><div class="section-head"><div><div class="eyebrow">Signature Astro Paquita</div><h2 class="section-title">Votre boussole</h2></div><p>Quatre repères seulement. Une case peut rester calme si le moteur ne trouve rien de suffisamment net.</p></div><div class="compass-list">${compassRow('Maintenant',today.s?`${today.tone} · ${today.domain}`:'Stable',today.s?`Signal ${today.s.niveau||'marqué'}`:'Aucun signal dominant suffisamment net')}${compassRow('Ensuite',tom.s?`${tom.tone} · ${tom.domain}`:'Stable',tom.s?'Demain':'Aucun signal dominant demain')}${compassRow('À garder en tête',watch?`${fmt(watch.date,{weekday:'long'})} · ${watch.domain}`:'Rien de particulier',watch?'Signal difficile fort ou exceptionnel dans les 7 jours':'Aucune vigilance forte détectée dans les 7 jours')}${compassRow('Plus loin','Mon année','Les grandes périodes seront raccordées au détecteur V121 sans approximation')}</div></section><div class="section-head"><div><div class="eyebrow">Aller plus loin</div><h2 class="section-title">Explorer sans se perdre</h2></div><button class="text-action" data-route="explore">Voir les usages spécialisés →</button></div></section>`}
function sky(){const p=state.profile;return `<section class="screen"><div class="eyebrow">Qui suis-je ?</div><h1 class="screen-title">Mon ciel</h1><p class="screen-intro">Le portrait natal sera organisé comme un portrait éditorial : grandes constantes, paradoxes, manière d’agir, monde émotionnel, relations, réalisation et ressources.</p>${p?`<div class="editorial-block"><h2>${esc(p.prenom||'Votre profil')}</h2><p>${esc([p.date,p.heure,p.ville].filter(Boolean).join(' · '))}</p></div>`:''}<div class="empty"><strong>Connexion au portrait natal V121 en cours.</strong><br>Cette page ne réutilisera aucun ancien écran. Les positions, maisons, aspects et dominantes viendront directement du moteur V121, puis seront présentés dans cette nouvelle structure.</div></section>`}
function now(){const days=state.days.slice(0,7).map(daySummary),t=days[0]||daySummary({date:dateAt(0),rows:[]}),y=state.days[-1];return `<section class="screen"><div class="eyebrow">Où en suis-je ?</div><h1 class="screen-title">Maintenant</h1><p class="screen-intro">Une lecture rapide d’abord. Le détail vient seulement si vous choisissez de l’ouvrir.</p><section class="sky-now"><div class="eyebrow">${esc(fmt(t.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}</div><div class="sentence">${esc(sentence(t.s))}</div><div class="meta"><span class="pill">${esc(t.tone)}</span>${t.s?`<span class="pill">${esc(t.domain)}</span>`:''}</div></section><section class="editorial-block"><h2>Votre semaine en 7 jours</h2><div class="week-strip">${days.map((x,i)=>`<div class="day ${i===0?'today':''}"><b>${esc(fmt(x.date))}</b><strong>${esc(x.tone)}</strong><small>${esc(x.domain)}</small></div>`).join('')}</div></section><section class="editorial-block"><h2>Ce qui ressort aujourd’hui</h2>${t.s?`<p>Le moteur classe ce signal « ${esc(t.s.niveau||'marqué')} ». Domaine principal : ${esc(t.domain)}. La lecture détaillée et les manifestations possibles seront générées à partir de ce signal, sans ajouter d’événement non calculé.</p>`:`<p class="quiet">Aucun signal suffisamment net ne justifie un développement particulier aujourd’hui.</p>`}</section></section>`}
function year(){return `<section class="screen"><div class="eyebrow">Qu’est-ce qui vient ensuite ?</div><h1 class="screen-title">Mon année</h1><p class="screen-intro">L’horizon principal sera de 12 mois. Les 24 mois ne seront qu’une vue « plus loin ».</p><div class="empty"><strong>Je ne fabrique pas encore la chronologie.</strong><br>Avant d’afficher cette page, l’adaptateur doit être raccordé au détecteur de périodes majeures V121 lui-même. Un simple balayage quotidien ou une nouvelle formule de score est volontairement interdit.</div></section>`}
function explore(){return `<section class="screen"><div class="eyebrow">Usages spécialisés</div><h1 class="screen-title">Explorer</h1><p class="screen-intro">Ici, on ne choisit pas un “module astrologique”. On part de ce que vous voulez comprendre ou décider.</p><div class="explore-list"><button class="explore-item"><div><h3>J’ai une décision à prendre</h3><p>Trouver des fenêtres adaptées à une intention précise, sans promettre de date parfaite.</p></div><span>→</span></button><button class="explore-item"><div><h3>Je veux comprendre une relation</h3><p>Ce qui rapproche, ce qui demande des ajustements et la manière dont chacun fonctionne dans le lien.</p></div><span>→</span></button><button class="explore-item"><div><h3>Je veux comprendre un enfant</h3><p>Forces, sensibilités, sécurité, apprentissage, autonomie et repères pour l’accompagner.</p></div><span>→</span></button><button class="explore-item"><div><h3>J’ai une question précise</h3><p>Une réponse directe d’abord, puis seulement les signaux utiles, les nuances et les périodes pertinentes.</p></div><span>→</span></button></div></section>`}
function profileModal(){const all=E().profiles(),active=E().activeKey();return `<div class="modal" data-close><div class="modal-box" onclick="event.stopPropagation()"><div class="section-head"><div><div class="eyebrow">Profil de naissance</div><h2>Choisir un profil</h2></div><button class="text-action" data-close>Fermer</button></div><div class="profile-list">${Object.entries(all).map(([k,p])=>`<button data-profile-key="${esc(k)}" class="${k===active?'active':''}"><strong>${esc(p.prenom||k)}</strong><br><small>${esc([p.date,p.heure,p.ville].filter(Boolean).join(' · '))}</small></button>`).join('')||'<p class="quiet">Aucun profil enregistré sur cet appareil.</p>'}</div></div></div>`}
function screen(){if(state.route==='sky')return sky();if(state.route==='now')return now();if(state.route==='year')return year();if(state.route==='explore')return explore();return home()}
function render(){document.getElementById('app').innerHTML=shell(screen());bind()}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{state.route=b.dataset.route;location.hash=state.route;render()}));document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{state.modal=true;render()}));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{state.modal=false;render()}));document.querySelectorAll('[data-profile-key]').forEach(b=>b.addEventListener('click',async()=>{await E().selectProfile(b.dataset.profileKey);state.profile=E().profile();state.modal=false;await loadSignals();render()}))}
async function loadSignals(){state.days=[];for(let i=0;i<7;i++){const date=dateAt(i);let rows=[];try{rows=await E().dailySignals(date,'marque')}catch(e){}state.days.push({date,rows})}}
async function boot(){state.route=(location.hash||'#home').slice(1);if(!ROUTES.some(x=>x[0]===state.route))state.route='home';render();try{await E().waitReady();state.engine=true;state.profile=E().profile();await loadSignals()}catch(e){state.error=e.message||String(e)}render()}
window.addEventListener('hashchange',()=>{state.route=(location.hash||'#home').slice(1);render()});boot();
})();