(function(){
'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Impossible de charger '+src));document.body.appendChild(s)})}
function renderMaintenance(message){const app=document.getElementById('app');app.innerHTML=`<main class="maintenance-screen"><div class="maintenance-card"><div class="maintenance-stars">✦ ☾ ✦</div><div class="maintenance-brand">Astro Paquita</div><div class="maintenance-rule"></div><h1>Le cabinet est momentanément fermé</h1><p>${esc(message||'Astro Paquita se refait une beauté. Le site sera de retour très bientôt.')}</p><small>Merci pour votre patience.</small></div></main>`}
async function canEnterDuringMaintenance(status){const m=status&&status.maintenance;if(!m||!m.enabled)return true;const qs=new URLSearchParams(location.search);if(qs.get('maintenance_preview')==='1')localStorage.setItem('astro-maintenance-bypass','1');if(localStorage.getItem('astro-maintenance-bypass')==='1')return true;const token=localStorage.getItem('astro-token');if(!token)return false;try{const r=await fetch('/api/me?ts='+Date.now(),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)return false;const u=await r.json();return !!(u&&(u.role==='admin'||u.is_admin||u.maintenance_allowed))}catch(e){return false}}
async function startApp(){const f=document.createElement('iframe');f.id='v121-engine';f.src='../engine/v121-host.html?engine=1';f.title='Moteur astrologique V121';f.hidden=true;document.body.appendChild(f);await loadScript('engine-adapter.js');await loadScript('access-policy.js');await loadScript('app.js')}
async function boot(){let status=null;try{const r=await fetch('/api/status?ts='+Date.now(),{cache:'no-store'});if(r.ok)status=await r.json()}catch(e){}if(status&&status.maintenance&&status.maintenance.enabled&&!await canEnterDuringMaintenance(status)){renderMaintenance(status.maintenance.message);return}try{await startApp()}catch(e){const app=document.getElementById('app');app.innerHTML=`<div class="boot-error"><strong>Astro Paquita n’a pas pu démarrer.</strong><p>${esc(e.message||e)}</p></div>`}}
boot();
})();
