(function(){
'use strict';
const ACTIVE_KEY='astro_paquita_profil_actif_v38';
const PROFILE_KEY='astra_profils';
let readyPromise=null;
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function frame(){return document.getElementById('v121-engine')}
function clone(v){try{return JSON.parse(JSON.stringify(v))}catch(e){return v}}
function text(el){return String(el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim()}
function localProfiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{}}catch(e){return{}}}
function activeKey(){const all=localProfiles(),k=localStorage.getItem(ACTIVE_KEY)||'';if(k&&all[k])return k;const keys=Object.keys(all);return keys.length===1?keys[0]:''}
function profile(){const all=localProfiles(),k=activeKey();return k?{key:k,...all[k]}:null}
function cacheMatchesProfile(cache,p){if(!cache?.meta||!cache?.fingerprint||!p)return false;const f=String(cache.fingerprint).split('|');if(p.prenom&&String(f[0]||'')!==String(p.prenom))return false;if(p.heure&&f[2]&&String(f[2])!==String(p.heure))return false;if(p.lat!=null&&f[3]&&Math.abs(Number(f[3])-Number(p.lat))>.0001)return false;if(p.lon!=null&&f[4]&&Math.abs(Number(f[4])-Number(p.lon))>.0001)return false;return true}
function cachedNatalFor(p){let best=null;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!k.startsWith('astro_paquita_natal_v100_'))continue;try{const x=JSON.parse(localStorage.getItem(k)||'null');if(cacheMatchesProfile(x,p)&&(!best||String(x.createdAt||'')>String(best.createdAt||'')))best=x}catch(e){}}return best}
async function waitReady(){if(readyPromise)return readyPromise;readyPromise=(async()=>{const f=frame();if(!f)throw new Error('Moteur V121 introuvable');for(let i=0;i<180;i++){try{const w=f.contentWindow;if(w&&typeof w.getProfils==='function'&&typeof w.apV51Signals==='function'&&typeof w.v37ChangerProfil==='function'){const k=activeKey();if(k)try{w.v37ChangerProfil(k)}catch(e){}try{if(typeof w.chargerStatutCompte==='function')await w.chargerStatutCompte()}catch(e){}return w}}catch(e){}await sleep(100)}throw new Error('Le moteur V121 ne répond pas')})();return readyPromise}
async function syncProfile(){const w=await waitReady(),k=activeKey();if(k)try{w.v37ChangerProfil(k)}catch(e){}return w}
async function selectProfile(key){const all=localProfiles();if(!all[key])return false;localStorage.setItem(ACTIVE_KEY,key);const w=await waitReady();try{w.v37ChangerProfil(key);return true}catch(e){return false}}
function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
async function v121Cities(){const w=await waitReady();try{const rows=w.eval('VILLES');return Array.isArray(rows)?clone(rows):[]}catch(e){return[]}}
async function searchCities(q){q=String(q||'').trim();if(q.length<2)return[];const out=[],seen=new Set(),add=r=>{if(!r||!Number.isFinite(Number(r.lat))||!Number.isFinite(Number(r.lon)))return;const k=`${normalize(r.nom)}|${normalize(r.pays)}`;if(seen.has(k))return;seen.add(k);out.push({label:r.label||`${r.nom} — ${r.pays}`,nom:r.nom,pays:r.pays,lat:Number(r.lat),lon:Number(r.lon),tz:r.tz||'Europe/Paris'})};try{const r=await fetch(`https://geo.api.gouv.fr/communes?nom=${encodeURIComponent(q)}&fields=nom,centre,codesPostaux,codeDepartement,codeRegion&boost=population&limit=6`);if(r.ok){const rows=await r.json();for(const c of rows||[]){if(c?.centre?.coordinates)add({label:`${c.nom} (${c.codesPostaux?.[0]||''} — France)`,nom:c.nom,pays:'France',lat:c.centre.coordinates[1],lon:c.centre.coordinates[0],tz:'Europe/Paris'})}}}catch(e){}const qn=normalize(q),local=await v121Cities();for(const v of local){if(out.length>=8)break;const hay=`${normalize(v.n)} ${normalize(v.p)}`;if(hay.includes(qn))add({label:`${v.n} — ${v.p}`,nom:v.n,pays:v.p,lat:v.lat,lon:v.lon,tz:v.tz})}return out.slice(0,8)}
function validateProfileData(data){const p={prenom:String(data?.prenom||'').trim(),date:String(data?.date||'').trim(),heure:String(data?.heure||'').trim(),ville:String(data?.ville||'').trim(),lat:String(data?.lat??'').trim(),lon:String(data?.lon??'').trim(),tz:String(data?.tz||'Europe/Paris').trim()||'Europe/Paris',genre:String(data?.genre||'N').trim()||'N'};if(!p.prenom)throw new Error('Prénom requis');if(!p.date)throw new Error('Date de naissance requise');if(!p.heure||!/^\d{1,2}:\d{2}$/.test(p.heure))throw new Error('Heure de naissance requise au format HH:MM');if(!p.ville)throw new Error('Ville de naissance requise');if(!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lon)))throw new Error('Sélectionnez une ville dans les résultats proposés');return p}
async function saveProfile(data,oldKey=''){const p=validateProfileData(data),w=await waitReady();const all=typeof w.getProfils==='function'?clone(w.getProfils()||{}):localProfiles();const key=`${p.prenom} (${p.date})`;const previous=oldKey&&all[oldKey]?all[oldKey]:null;if(previous?.life_context)p.life_context=clone(previous.life_context);all[key]=p;if(oldKey&&oldKey!==key)delete all[oldKey];if(typeof w.setProfils==='function')w.setProfils(all);else localStorage.setItem(PROFILE_KEY,JSON.stringify(all));localStorage.setItem(ACTIVE_KEY,key);try{if(typeof w.rafraichirSelectProfils==='function')w.rafraichirSelectProfils()}catch(e){}try{if(typeof w.rafraichirSelectProfilsSynastrie==='function')w.rafraichirSelectProfilsSynastrie()}catch(e){}try{if(typeof w.v37RafraichirSelectProfil==='function')w.v37RafraichirSelectProfil(key)}catch(e){}if(!w.v37ChangerProfil(key))throw new Error('Le moteur V121 n’a pas pu charger ce profil');return {key,...p}}
async function deleteProfile(key){const w=await waitReady(),all=typeof w.getProfils==='function'?clone(w.getProfils()||{}):localProfiles();if(!all[key])return false;delete all[key];if(typeof w.setProfils==='function')w.setProfils(all);else localStorage.setItem(PROFILE_KEY,JSON.stringify(all));const remaining=Object.keys(all);let next=remaining[0]||'';if(localStorage.getItem(ACTIVE_KEY)===key){if(next)localStorage.setItem(ACTIVE_KEY,next);else localStorage.removeItem(ACTIVE_KEY)}try{if(typeof w.rafraichirSelectProfils==='function')w.rafraichirSelectProfils()}catch(e){}try{if(typeof w.rafraichirSelectProfilsSynastrie==='function')w.rafraichirSelectProfilsSynastrie()}catch(e){}try{if(typeof w.v37RafraichirSelectProfil==='function')w.v37RafraichirSelectProfil(next)}catch(e){}if(next)try{w.v37ChangerProfil(next)}catch(e){}return true}
function normalizeSignals(rows){return (rows||[]).map(x=>({date:x.date,domain:x.domain,label:x.label,polarite:x.polarite,niveau:x.niveau,force:Number(x.force||0),strength:Number(x.strength||0),families:Array.isArray(x.coreFamilies)&&x.coreFamilies.length?x.coreFamilies:(x.families||[]),scenarios:Array.isArray(x.scenarios)?x.scenarios:[]}))}
async function dailySignals(date,minLevel='marque'){const w=await syncProfile();try{return normalizeSignals(w.apV51Signals(date,minLevel)||[])}catch(e){return[]}}
async function monthlyTrends(){return null}
async function natalTechnical(){await syncProfile();const c=cachedNatalFor(profile());return c?.meta?clone(c.meta):null}
async function natalTechnicalFor(key){await waitReady();const p=localProfiles()[key];if(!p)throw new Error('Profil introuvable');const c=cachedNatalFor(p);return c?.meta?clone(c.meta):null}
async function prepareNatalFor(key){const all=localProfiles(),p=all[key];if(!p)throw new Error('Profil introuvable');const old=activeKey(),w=await waitReady();try{localStorage.setItem(ACTIVE_KEY,key);w.v37ChangerProfil(key);if(typeof w.genererNatal!=='function')throw new Error('Portrait natal V121 indisponible');await w.genererNatal(false);const c=cachedNatalFor(p);if(!c?.meta)throw new Error('Le moteur V121 n’a pas produit les données natales');return {meta:clone(c.meta),text:String(c.text||'')}}finally{if(old&&all[old]){localStorage.setItem(ACTIVE_KEY,old);try{w.v37ChangerProfil(old)}catch(e){}}}}
async function prepareNatal(){const k=activeKey();if(!k)throw new Error('Aucun profil sélectionné');return prepareNatalFor(k)}
async function account(){const token=localStorage.getItem('astro-token');if(!token)return null;try{const r=await fetch('/api/me?ts='+Date.now(),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)return null;return await r.json()}catch(e){return null}}
async function premium(){const a=await account();return !!(a&&(a.premium||a.role==='admin'||a.is_admin))}
async function login(email,password){const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,motDePasse:password})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.erreur||data.error||'Connexion impossible');const token=data.token||data.access_token;if(!token)throw new Error('Jeton de connexion absent');localStorage.setItem('astro-token',token);readyPromise=null;return data}
async function signup(email,password,prenom){const r=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,motDePasse:password,prenom})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.erreur||data.error||'Inscription impossible');const token=data.token||data.access_token;if(token)localStorage.setItem('astro-token',token);readyPromise=null;return data}
function logout(){localStorage.removeItem('astro-token');localStorage.removeItem('astro-admin-key');readyPromise=null}
async function ai(payload){const token=localStorage.getItem('astro-token');if(!token)throw new Error('Connexion requise');const headers={'Content-Type':'application/json','Authorization':'Bearer '+token};const admin=localStorage.getItem('astro-admin-key');if(admin)headers['x-admin-key']=admin;const r=await fetch('/api/claude',{method:'POST',headers,body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.erreur||data.error||'Analyse indisponible');return data}
async function syncAccountInEngine(w){try{if(typeof w.chargerStatutCompte==='function')await w.chargerStatutCompte()}catch(e){}}
async function events24(){const w=await syncProfile();await syncAccountInEngine(w);if(!await premium())throw new Error('Fonction Premium');if(typeof w.genererEvenements!=='function')throw new Error('Détecteur V121 indisponible');try{if(typeof w.resetEvenements==='function')w.resetEvenements()}catch(e){}await w.genererEvenements();const d=w.document,box=d.getElementById('ev-alertes');const cards=[...(box?.querySelectorAll('.ev-card')||[])].map(c=>({title:text(c.querySelector('.ev-card-titre')),trend:text(c.querySelector('.ev-trend')),domain:text(c.querySelector('.ev-domain-tag')),period:[...c.querySelectorAll('.ev-period-line')].map(text),details:[...c.querySelectorAll('.ev-card-desc,.ev-scenario,.ev-concrete-list li,.ev-concrete-item')].map(text).filter(Boolean),raw:text(c)}));return {cards,summary:text(d.getElementById('ev-rapport')),title:text(d.querySelector('.ev-hero-title')),subtitle:text(d.querySelector('.ev-hero-sub'))}}
async function timing(intention){const w=await syncProfile();await syncAccountInEngine(w);if(!await premium())throw new Error('Fonction Premium');if(typeof w.lancerFenetre!=='function'||typeof w.selIntent!=='function')throw new Error('Moteur de timing V121 indisponible');try{if(typeof w.resetFenetre==='function')w.resetFenetre()}catch(e){}const engineIntent=intention==='rencontre'?'amour':intention;const buttons=[...w.document.querySelectorAll('#f-intentions .f-btn')];const btn=buttons.find(b=>String(b.getAttribute('onclick')||'').includes("'"+engineIntent+"'"));if(!btn)throw new Error('Intention non prise en charge par V121');w.selIntent(engineIntent,btn);await w.lancerFenetre();const d=w.document;return {title:text(d.getElementById('f-res-titre')),subtitle:text(d.getElementById('f-res-sous')),windows:[...(d.getElementById('f-fenetres')?.children||[])].map(text).filter(Boolean),report:text(d.getElementById('f-rapport'))}}
async function relation(otherKey,type='couple'){const w=await syncProfile();await syncAccountInEngine(w);if(!await premium())throw new Error('Fonction Premium');if(typeof w.analyserSynastrie!=='function'||typeof w.chargerProfilSynastrie!=='function')throw new Error('Synastrie V121 indisponible');const d=w.document;try{if(typeof w.resetSynastrie==='function')w.resetSynastrie()}catch(e){}try{if(typeof w.rafraichirSelectProfilsSynastrie==='function')w.rafraichirSelectProfilsSynastrie()}catch(e){}const sel=d.getElementById('y-profils-select');if(!sel)throw new Error('Sélecteur de relation indisponible');sel.value=otherKey;if(sel.value!==otherKey)throw new Error('Le second profil n’est pas disponible dans V121');w.chargerProfilSynastrie();const typ=d.getElementById('y-type-relation');if(typ){typ.value=type;try{if(typeof w.yActualiserTypeSynastrieV26==='function')w.yActualiserTypeSynastrieV26()}catch(e){}}await w.analyserSynastrie();return {title:text(d.getElementById('y-res-titre')),subtitle:text(d.getElementById('y-res-sous')),report:text(d.getElementById('y-rapport')),periods:text(d.getElementById('y-fenetres'))}}
async function question(q,domain='general'){const w=await syncProfile();await syncAccountInEngine(w);const a=await account();if(!a)throw new Error('Connexion requise');if(typeof w.poserQuestion!=='function')throw new Error('Module question V121 indisponible');const d=w.document;const input=d.getElementById('q-texte');if(!input)throw new Error('Question V121 indisponible');input.value=q;if(domain&&domain!=='general'&&typeof w.selDomQ==='function'){const bs=[...d.querySelectorAll('#q-domaines .dom-btn')];const b=bs.find(x=>String(x.getAttribute('onclick')||'').includes("'"+domain+"'"));if(b)w.selDomQ(domain,b)}await w.poserQuestion();return {title:text(d.getElementById('q-res-titre')),subtitle:text(d.getElementById('q-res-sous')),report:text(d.getElementById('q-rapport'))}}
function diagnostics(){return {activeKey:activeKey(),profiles:Object.keys(localProfiles()).length,token:!!localStorage.getItem('astro-token'),engine:!!frame()?.contentWindow}}
window.AstroEngine={waitReady,profiles:localProfiles,activeKey,profile,selectProfile,searchCities,saveProfile,deleteProfile,dailySignals,monthlyTrends,natalTechnical,natalTechnicalFor,prepareNatal,prepareNatalFor,events24,timing,relation,question,account,premium,login,signup,logout,ai,diagnostics,version:'V121'};
})();
