(function(){
'use strict';
const E=window.AstroEngine;
if(!E)throw new Error('Onboarding : moteur indisponible');
let resolveReady=null,timer=null,results=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function app(){return document.getElementById('app')}
function profiles(){return E.profiles()||{}}
function active(){return E.activeKey()||''}
function field(name,label,placeholder='',extra=''){return`<label class="ob-field"><span>${esc(label)}</span><input name="${esc(name)}" placeholder="${esc(placeholder)}" ${extra}></label>`}
function renderChoice(){const all=profiles();app().innerHTML=`<main class="ob-screen"><section class="ob-card"><div class="ob-brand">Astro Paquita<small>Votre ciel, simplement</small></div><div class="ob-kicker">Avant de commencer</div><h1>Choisissez votre profil</h1><p>Plusieurs profils existent déjà sur cet appareil, mais aucun n’est actuellement sélectionné. Aucun calcul ne sera affiché tant que vous n’avez pas choisi.</p><div class="ob-existing">${Object.entries(all).map(([k,p])=>`<button data-ob-select="${esc(k)}"><strong>${esc(p.prenom||k)}</strong><small>${esc([p.date,p.heure,p.ville].filter(Boolean).join(' · '))}</small></button>`).join('')}</div><button class="ob-link" data-ob-new>+ Créer un nouveau profil</button></section></main>`;bindChoice()}
function renderCreate(values={}){const v={prenom:'',date:'',heure:'',ville:'',lat:'',lon:'',tz:'Europe/Paris',genre:'N',...values};app().innerHTML=`<main class="ob-screen"><section class="ob-card"><div class="ob-brand">Astro Paquita<small>Votre ciel, simplement</small></div><div class="ob-kicker">Première étape</div><h1>Votre profil de naissance</h1><p>Astro Paquita a besoin de la date, de l’heure et du lieu de naissance avant d’afficher votre ciel. Les calculs restent ceux du moteur V121.</p><form id="ob-form" class="ob-form"><input type="hidden" name="lat" value="${esc(v.lat)}"><input type="hidden" name="lon" value="${esc(v.lon)}"><input type="hidden" name="tz" value="${esc(v.tz)}">${field('prenom','Prénom','Votre prénom','required autocomplete="off" value="'+esc(v.prenom)+'"')}<div class="ob-grid">${field('date','Date de naissance','JJ/MM/AAAA','required inputmode="numeric" value="'+esc(v.date)+'"')}${field('heure','Heure de naissance','HH:MM','required inputmode="numeric" value="'+esc(v.heure)+'"')}</div><label class="ob-field"><span>Ville de naissance</span><div class="ob-city"><input name="ville" placeholder="Commencez à taper une ville…" required autocomplete="off" value="${esc(v.ville)}">${results.length?`<div class="ob-results">${results.map((c,i)=>`<button type="button" data-ob-city="${i}"><strong>${esc(c.label)}</strong><small>${esc(c.tz)}</small></button>`).join('')}</div>`:''}</div></label>${v.lat&&v.lon?`<div class="ob-coord">✓ ${Number(v.lat).toFixed(4)}, ${Number(v.lon).toFixed(4)} · ${esc(v.tz)}</div>`:'<div class="ob-note">Sélectionnez une ville proposée pour conserver les coordonnées et le fuseau V121.</div>'}<label class="ob-field"><span>Genre</span><select name="genre"><option value="N" ${v.genre==='N'?'selected':''}>Non renseigné / autre</option><option value="F" ${v.genre==='F'?'selected':''}>Femme</option><option value="H" ${v.genre==='H'?'selected':''}>Homme</option></select></label><div id="ob-error" class="ob-error" hidden></div><button class="ob-primary">Créer mon profil et continuer</button></form>${Object.keys(profiles()).length?'<button class="ob-link" data-ob-back>← Choisir un profil existant</button>':''}</section></main>`;bindCreate()}
function formValues(form){const f=new FormData(form);return{prenom:String(f.get('prenom')||''),date:String(f.get('date')||''),heure:String(f.get('heure')||''),ville:String(f.get('ville')||''),lat:String(f.get('lat')||''),lon:String(f.get('lon')||''),tz:String(f.get('tz')||'Europe/Paris'),genre:String(f.get('genre')||'N')}}
function finish(){if(resolveReady){const r=resolveReady;resolveReady=null;r(true)}}
function bindChoice(){document.querySelectorAll('[data-ob-select]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await E.selectProfile(b.dataset.obSelect);finish()}catch(e){b.disabled=false}}));document.querySelector('[data-ob-new]')?.addEventListener('click',()=>renderCreate())}
function bindCreate(){const form=document.getElementById('ob-form'),city=form?.querySelector('[name="ville"]');document.querySelector('[data-ob-back]')?.addEventListener('click',renderChoice);city?.addEventListener('input',()=>{const lat=form.querySelector('[name="lat"]'),lon=form.querySelector('[name="lon"]'),tz=form.querySelector('[name="tz"]');lat.value='';lon.value='';tz.value='Europe/Paris';results=[];clearTimeout(timer);const q=city.value.trim(),snapshot=formValues(form);if(q.length<2)return;timer=setTimeout(async()=>{try{results=await E.searchCities(q);if(document.getElementById('ob-form'))renderCreate({...snapshot,ville:q,lat:'',lon:'',tz:'Europe/Paris'})}catch(e){}},350)});document.querySelectorAll('[data-ob-city]').forEach(b=>b.addEventListener('click',()=>{const c=results[Number(b.dataset.obCity)],snapshot=formValues(form);if(!c)return;results=[];renderCreate({...snapshot,ville:`${c.nom} (${c.pays})`,lat:String(c.lat),lon:String(c.lon),tz:c.tz||'Europe/Paris'})}));form?.addEventListener('submit',async e=>{e.preventDefault();const err=document.getElementById('ob-error'),btn=form.querySelector('button[type="submit"],.ob-primary');if(err){err.hidden=true;err.textContent=''}if(btn)btn.disabled=true;try{await E.saveProfile(formValues(form));finish()}catch(ex){if(err){err.textContent=ex.message||String(ex);err.hidden=false}if(btn)btn.disabled=false}})}
async function ensureProfile(){await E.waitReady();if(active())return true;return new Promise(resolve=>{resolveReady=resolve;const all=profiles();if(Object.keys(all).length)renderChoice();else renderCreate()})}
if(typeof E.deleteProfile==='function'){
  const baseDelete=E.deleteProfile.bind(E);
  E.deleteProfile=async function(key){const ok=await baseDelete(key);if(ok&&Object.keys(profiles()).length===0)setTimeout(()=>location.reload(),0);return ok};
}
window.AstroOnboarding={ensureProfile};
})();
